### ISSUE TITLE
IOError: [Errno 2] No such file or directory: when trying to send SMS

### ISSUE THREAD

**Issue by damago1** [lvasiliev/smstools-http-api#17]
When trying to send my first SMS via command entered directly from readme.md
I am getting either python recursion error (mentioned in other issue) or a webpage with error:

`IOError: [Errno 2] No such file or directory: 'tmp/outgoing/40fabae2-7edb-4092-a603-d580da0fece7.LOCK'`

The full error dump is:

```
IOError
IOError: [Errno 2] No such file or directory: 'tmp/outgoing/40fabae2-7edb-4092-a603-d580da0fece7.LOCK'

Traceback (most recent call last)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2463, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2449, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1866, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/dist-packages/flask_httpauth.py", line 105, in decorated
return f(*args, **kwargs)
File "/root/smstools-http-api-master/app/api_1_0/views.py", line 76, in outgoing_view
result = send_sms(data)
File "/root/smstools-http-api-master/app/api_1_0/smstools.py", line 160, in send_sms
with open(lock_file, write_mode) as fp:
IOError: [Errno 2] No such file or directory: 'tmp/outgoing/40fabae2-7edb-4092-a603-d580da0fece7.LOCK'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

```

**Comment by damago1** [comment]
I have no idea where this tmp folder should be created. Or what is the other reason for this.
